[package]
name = "yapg"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true

syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
heck.workspace = true
logos.workspace = true