[package]
name = "yall"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

syn = { version = "2", features = ["full", "parsing"] }
quote = "1"
proc-macro2 = "1"
heck = "0.4"