[package]
name = "yapg-test"
version = "0.1.0"
edition = "2024"

[dependencies]
yapg = { path = "../yapg" }
phf = { version = "0.12", features = ["macros"] }

tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
yapg = { path = "../yapg" }
